// Writes lib/config/firebase_options_prod.dart (not committed) for the live
// Firebase project, for iOS, Android and the web.
//
// Run from the project folder, signed in with the Firebase CLI:
//   node tool/generate_firebase_options.mjs
//
// iOS and Android values come from the config files in the repository; the
// web values are fetched with the Firebase CLI (a web app is created in the
// project if there is none yet).
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const PROJECT = "flashpedz-faisal";

function firebase(...args) {
  const out = execFileSync("firebase", [...args, "--project", PROJECT, "--json"], {
    encoding: "utf8",
  });
  const parsed = JSON.parse(out);
  if (parsed.status !== "success") {
    throw new Error(`firebase ${args.join(" ")} failed: ${out}`);
  }
  return parsed.result;
}

/** Finds `key` anywhere in a (possibly nested) value. */
function find(value, key) {
  if (value && typeof value === "object") {
    if (typeof value[key] === "string") return value[key];
    for (const child of Object.values(value)) {
      const found = find(child, key);
      if (found) return found;
    }
  }
  if (typeof value === "string") {
    const match = value.match(new RegExp(`["']?${key}["']?\\s*[:=]\\s*["']([^"']+)["']`));
    if (match) return match[1];
  }
  return undefined;
}

function plistValue(plist, key) {
  const match = plist.match(new RegExp(`<key>${key}</key>\\s*<string>([^<]*)</string>`));
  if (!match) throw new Error(`${key} missing from GoogleService-Info.plist`);
  return match[1];
}

// iOS
const plist = readFileSync("ios/Runner/GoogleService-Info.plist", "utf8");
const ios = {
  apiKey: plistValue(plist, "API_KEY"),
  appId: plistValue(plist, "GOOGLE_APP_ID"),
  messagingSenderId: plistValue(plist, "GCM_SENDER_ID"),
  projectId: plistValue(plist, "PROJECT_ID"),
  storageBucket: plistValue(plist, "STORAGE_BUCKET"),
  iosBundleId: plistValue(plist, "BUNDLE_ID"),
};

// Android
const services = JSON.parse(
  readFileSync("android/app/src/prod/google-services.json", "utf8"),
);
const client = services.client[0];
const android = {
  apiKey: client.api_key[0].current_key,
  appId: client.client_info.mobilesdk_app_id,
  messagingSenderId: services.project_info.project_number,
  projectId: services.project_info.project_id,
  storageBucket: services.project_info.storage_bucket,
};

// Web
let webApps = firebase("apps:list", "WEB");
if (!Array.isArray(webApps) || webApps.length === 0) {
  console.log("No web app in the Firebase project yet, creating one...");
  firebase("apps:create", "WEB", "FlashPedz Web");
  webApps = firebase("apps:list", "WEB");
}
const webAppId = webApps[0].appId;
const webConfig = firebase("apps:sdkconfig", "WEB", webAppId);
const web = {
  apiKey: find(webConfig, "apiKey"),
  appId: find(webConfig, "appId") ?? webAppId,
  messagingSenderId: find(webConfig, "messagingSenderId"),
  projectId: find(webConfig, "projectId"),
  authDomain: find(webConfig, "authDomain"),
  storageBucket: find(webConfig, "storageBucket"),
  measurementId: find(webConfig, "measurementId"),
};

for (const [name, config] of Object.entries({ ios, android, web })) {
  for (const key of ["apiKey", "appId", "messagingSenderId", "projectId"]) {
    if (!config[key]) throw new Error(`Missing ${key} for ${name}`);
  }
}

function options(config) {
  return Object.entries(config)
    .filter(([, value]) => value)
    .map(([key, value]) => `    ${key}: '${value}',`)
    .join("\n");
}

writeFileSync(
  "lib/config/firebase_options_prod.dart",
  `// Generated by tool/generate_firebase_options.mjs, don't edit by hand.
// Firebase settings for the live app (project ${PROJECT}).
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    if (defaultTargetPlatform == TargetPlatform.android) return android;
    return ios;
  }

  static const FirebaseOptions android = FirebaseOptions(
${options(android)}
  );

  static const FirebaseOptions ios = FirebaseOptions(
${options(ios)}
  );

  static const FirebaseOptions web = FirebaseOptions(
${options(web)}
  );
}
`,
);
console.log(
  `Wrote lib/config/firebase_options_prod.dart (web app ${webAppId}, key length ${web.apiKey.length}).`,
);
